### ISSUE TITLE
Virtual Provides aren't addressed in components

### ISSUE THREAD

**Issue by nathanhan** [modularity-modules/shared-userspace#5]
Specifically for the base-runtime module but possibly the case for shared-userspace (i couldnt find base-runtime on github), certain packages are dependencies of base-runtime but not included in the yaml file for base-runtime. For example, base-runtime depends on fedora-release, which is not included in the modulemd file.

**Comment by TomasTomecek** [comment]
This is upstream for base runtime: https://github.com/fedora-modularity/base-runtime

Which package from the module requires fedora-release specifically?

base runtime module includes fedora-modular-release: http://pkgs.fedoraproject.org/cgit/modules/base-runtime.git/tree/base-runtime.yaml#n150

**Comment by nathanhan** [comment]
I might be referencing the wrong section of the baseruntime modulemd file. Should I be looking at the component.rpms or the api.rpms when I am looking for the packages included in the baseruntime module?
I have a few other examples for base runtime.
nss-softokn (inside baseruntime.component.rpms) requires nss-softokn-freebl (not inside baseruntime.component.rpms but is inside baseruntime.api.rpms)
nss-softokn (inside baseruntime.component.rpms) requires sqlite-libs (not inside baseruntime.component.rpms but is inside baseruntime.api.rpms)

**Comment by TomasTomecek** [comment]
@nathanhan what you're experiencing is the difference between source RPM and binary RPM: components.rpms is a list of source RPMs -- these are then built and turned into a list of binary RPMs, which you can observe in api.rpms. An example:

Here is [a build of source RPM nss-softokn](https://koji.fedoraproject.org/koji/buildinfo?buildID=917549), it produces binary rpms:
* nss-softokn-3.30.2-1.0.module_63449d3a.x86_64.rpm
* nss-softokn-devel-3.30.2-1.0.module_63449d3a.x86_64.rpm
* nss-softokn-freebl-3.30.2-1.0.module_63449d3a.x86_64.rpm
* nss-softokn-freebl-devel-3.30.2-1.0.module_63449d3a.x86_64.rpm
* nss-softokn-debuginfo-3.30.2-1.0.module_63449d3a.x86_64.rpm

As you can see, `nss-softokn-freebl` is there and the key here is to ensure that since `nss-softokn` requires `nss-softokn-freebl`, `nss-softokn-freebl` is included in api.rpms and *not* in filter.rpms.

Guys from base-runtime have tools to ensure that these dependencies are satisfied. @sgallagher @ignatenkobrain would you be able to give Nathan a brief a intro of what tools you are using to make sure that depedencies of all rpms within a module are satisfied? Thank you!

**Comment by ignatenkobrain** [comment]
Well, we use depchase to *create* modulemd, so at that point there are 0 missing dependencies. Then there is some manual filtering (not sure) and then pungi ensures through repoclosure that all dependencies are satisfied.

Unfortunately I don't understand what this issue is all about =(

cc @contyk

**Comment by asamalik** [comment]
@nathanhan modulemd is a build recipe. The `rpms` section references source packages. Each source package can be built into one or more binaries. These binaries, however, are not all mentioned in the modulemd - just some of them. Let me explain.

The `api` lists all the binary packages which are the "main" packages of the module. All others (which are not mentioned) are just dependencies - an implementation detail, and users should not use anything else than the `api` packages.

Then there is `filter`. It also lists binary packages, but these packages are filtered out - not shipped to the user.

You can find the complete list of binaries in PDC. For example, see the [PDC entry for the nginx module](https://pdc.fedoraproject.org/rest_api/v1/unreleasedvariants/?active=True&variant_name=nginx). The binary packages are listed in the `results.rpms` field. You can edit the url to see another modules.


**An example:**

Let's assume there are two packages, `package1` and `package2`. These are source packages and build into multiple binaries:

```
package1:
  ->  package1
  ->  package1-extras
  ->  package1-devel

package2:
  ->  package2
  ->  package2-devel
```

You have the following modulemd:

```
components:
    rpms:
        package1:
            rationale: An example package.
            ref: f26
        package2:
            rationale: An example package.
            ref: f26
api:
    rpms:
        - package1
        - package2

filter:
    rpms:
        - package1-devel
        - package2-devel
```

The binary packages coming out of this module wil be:

```
package1
package1-extras
package2
```

As you can see, the `package1-extras` is not mentioned in the modulemd.

**Comment by contyk** [comment]
I don't understand what virtual provides mean in this context. But as others have already pointed out, this stems from misunderstanding some of the concepts, namely the differences between source and binary package names. Tomáš and Adam have already covered that.

The Base Runtime module was generated with the help of the `depchase` "solver". We included all the source packages needed to build the binary packages we cared about in the components section. We then checked what subpackages their corresponding builds produced and included everything (both through inaction, i.e. not filtering them out, and in the API) that wasn't pulling in additional dependencies (well, this was a little more complex than that -- sometimes we added new packages if the extent of such changes was very limited and it made sense overall). Finally we filtered out subpackages we couldn't include due to their dependencies not being satisfied.

As far as I know, the Base Runtime module doesn't have any runtime dependency issues but if you find anything, let us know.

**Comment by asamalik** [comment]
@nathanhan regarding to the `fedora-release` dependency, there is another fact that needs to be taken into account. There might be one or more packages satisfying one dependency.

For example, there are three packages that would satisfy the same dependency:

* `fedora-release`
* `generic-release`
* `fedora-modular-release` <- in base runtime

When you use `repoquery` to resolve individual package dependnecies (like my [modularity-dep-viz](https://github.com/asamalik/modularity-dep-viz) script does), you won't always get the right result, because it will choose one of these at "random", without looking at what's already available. It was easy to implement, but it doesn't always get the right result.

If you, however, use `libsolv` to resolve all the dependencies at one (like [depchase](https://github.com/fedora-modularity/depchase) does), you will always get the right result, because it can see all the dependencies in one context. This is harder to implement, but it always get the right result.

Our `libsolv` guru is @ignatenkobrain - talk to him ;)

**Comment by alexxa** [comment]
@nathanhan @asamalik @contyk @TomasTomecek @ignatenkobrain is this issue still valid? please update its status or close, thank you!

**Comment by ignatenkobrain** [comment]
@alexxa this module is dead.

**Comment by whitel** [comment]
closing as invlid
